server:
  port: 8080
  servlet:
    context-path: /car

spring:
#mvc:
#  pathmatch:
#    matching-strategy: ant_path_matcher
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
  datasource:
    initialization-mode: always
    driver-class-name: org.h2.Driver
    schema: classpath:schema.sql
    data: classpath:data.sql
    url: jdbc:h2:file:./data/dbAccount
    username: root
    password: root
    platform: org:hibernate:dialect:H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-admin
      settings:
        trace: false
        web-allow-others: false